server:
port: ${PORT:8085}
address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://crossover.proxy.rlwy.net:31377/railway
    username: postgres
    password: nMpDMwZgOKrKFsRiJjByypIMgHLgdXIb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
